import { build } from "esbuild";
import { solidPlugin } from "esbuild-plugin-solid";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const result = await build({
  entryPoints: ["src/client/index.tsx"],
  bundle: true,
  format: "esm",
  minify: true,
  write: false,
  plugins: [solidPlugin()],
  // Inline CSS
  loader: { ".css": "text" },
});

const code = result.outputFiles[0].text;

// Generate a TypeScript file that exports the bundled code as a string
const output = `// Auto-generated by scripts/build-client.js - do not edit
export const clientBundle = ${JSON.stringify(code)};
`;

const outPath = "src/generated/client-bundle.ts";
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, output);

console.log(`✓ Client bundle written to ${outPath} (${code.length} bytes)`);
