import { build, context } from "esbuild";
import { solidPlugin } from "esbuild-plugin-solid";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const watchMode = process.argv.includes("--watch");
const outPath = "src/generated/client-bundle.ts";

function writeBundle(code) {
  const output = `// Auto-generated by scripts/build-client.js - do not edit
export const clientBundle = ${JSON.stringify(code)};
`;
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, output);
  console.log(`✓ Client bundle written to ${outPath} (${code.length} bytes)`);
}

const buildOptions = {
  entryPoints: ["src/client/index.tsx"],
  bundle: true,
  format: "esm",
  minify: !watchMode,
  write: false,
  plugins: [solidPlugin()],
  loader: { ".css": "text" },
};

if (watchMode) {
  // Watch mode: rebuild on changes
  const ctx = await context({
    ...buildOptions,
    plugins: [
      ...buildOptions.plugins,
      {
        name: "bundle-writer",
        setup(build) {
          build.onEnd((result) => {
            if (result.outputFiles?.[0]) {
              writeBundle(result.outputFiles[0].text);
            }
          });
        },
      },
    ],
  });
  await ctx.watch();
  console.log("Watching for changes...");
} else {
  // Single build
  const result = await build(buildOptions);
  writeBundle(result.outputFiles[0].text);
}
