// Code generated by tygor. DO NOT EDIT.

/** Page is a generic paginated response. */
export interface Page<T> {
  items?: T[];
  total: number /* int */;
  hasMore: boolean;
}
/** Profile contains optional user profile information. */
export interface Profile {
  bio: string;
  avatar?: string;
  links?: Record<string, string>;
}
/** Role represents the access level of a user. */
export type Role = "admin" | "editor" | "viewer";
/** User represents a user in the system. */
export interface User {
  id: string;
  email: string;
  role: Role;
  /** Profile is nil for users who haven't completed onboarding. */
  profile?: Profile;
  tags?: string[];
  metadata?: Record<string, unknown>;
  createdAt: string /* RFC3339 */;
}
