// Code generated by tygor. DO NOT EDIT.

/** AuditEvent records an action in the system. */
export interface AuditEvent {
  id: string;
  "type": EventType;
  actorId: string;
  targetId: string;
  metadata?: Record<string, unknown>;
  timestamp: string /* RFC3339 */;
}
/** EventType categorizes audit events. */
export type EventType = "team.created" | "user.created" | "user.deleted" | "user.updated";
/** Member represents a user's membership in a team. */
export interface Member {
  userId: string;
  role: TeamRole;
  joinedAt: string /* RFC3339 */;
}
/** PageInfo contains pagination metadata for responses. */
export interface PageInfo {
  totalCount: number /* int */;
  hasNextPage: boolean;
  hasPrevPage: boolean;
}
/** PaginatedUsers wraps a user list with pagination info. */
export interface PaginatedUsers {
  users?: User[];
  pageInfo: PageInfo;
}
/** Pagination contains common pagination parameters. */
export interface Pagination {
  page: number /* int */;
  pageSize: number /* int */;
}
/** Profile contains optional user profile information. */
export interface Profile {
  bio: string;
  avatarUrl?: string;
  links?: Record<string, string>;
  settings: Settings;
}
/** Role represents the access level of a user. */
export type Role = "admin" | "editor" | "viewer";
/** Settings holds user preferences. */
export interface Settings {
  theme: Theme;
  locale: string;
  emailDigest: boolean;
  itemsPerPage: number /* int */;
}
/** Team groups users together. */
export interface Team {
  id: string;
  name: string;
  members?: Member[];
}
/** TeamRole defines permissions within a team. */
export type TeamRole = "guest" | "member" | "owner";
/** Theme represents UI color schemes. */
export type Theme = "dark" | "light" | "system";
/** User represents a user in the system. */
export interface User {
  id: string;
  email: string;
  name: string;
  role: Role;
  profile?: Profile;
  tags?: string[];
  createdAt: string /* RFC3339 */;
}
