// Code generated by tygor. DO NOT EDIT.

/**
 * CreateTaskRequest contains the data needed to create a new task.
 * @see github.com/broady/tygor/examples/config-showcase/api/types.go#CreateTaskRequest
 */
export interface CreateTaskRequest {
  title: string;
  description: string | null;
  priority: Priority;
  assignee: string | null;
  tags: string[] | null;
}
/**
 * ListTasksParams contains query parameters for listing tasks.
 * @see github.com/broady/tygor/examples/config-showcase/api/types.go#ListTasksParams
 */
export interface ListTasksParams {
  /** Status filters tasks by their current status. */
  status: Status | null;
  /** Assignee filters tasks by assigned user. */
  assignee: string | null;
  /** Limit is the maximum number of results. */
  limit: number /* int */ | null;
  /** Offset is the pagination offset. */
  offset: number /* int */ | null;
}
/**
 * Priority represents task urgency levels.
 * @see github.com/broady/tygor/examples/config-showcase/api/types.go#Priority
 */
export type Priority = 4 | 3 | 1 | 2;
/**
 * Status represents the state of a task.
 * @see github.com/broady/tygor/examples/config-showcase/api/types.go#Status
 */
export type Status = "cancelled" | "completed" | "in_progress" | "pending";
/**
 * Task represents a work item in the system.
 * @see github.com/broady/tygor/examples/config-showcase/api/types.go#Task
 */
export interface Task {
  /** ID is the unique identifier for the task. */
  id: string;
  /** Title is the task's headline. */
  title: string;
  /** Description is the detailed task description. */
  description: string | null;
  /** Status is the current state of the task. */
  status: Status;
  /** Priority determines the task's urgency. */
  priority: Priority;
  /** Assignee is the user responsible for the task. */
  assignee: string | null;
  /** DueDate is when the task should be completed. */
  due_date: string /* RFC3339 */ | null;
  /** Tags are labels for categorization. */
  tags: string[] | null;
  /** CreatedAt is when the task was created. */
  created_at: string /* RFC3339 */;
}
