// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "Devtools.Info": {
    req: Record<string, never>;
    res: types.InfoResponse;
  };
  "Devtools.Ping": {
    req: Record<string, never>;
    res: types.PingResponse;
  };
  "Devtools.Status": {
    req: types.StatusRequest;
    res: types.StatusResponse;
  };
}

const metadata = {
  "Devtools.Info": { path: "/Devtools/Info", primitive: "query" },
  "Devtools.Ping": { path: "/Devtools/Ping", primitive: "query" },
  "Devtools.Status": { path: "/Devtools/Status", primitive: "query" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
