// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "Devtools.Info": {
    req: Record<string, never>;
    res: (types.InfoResponse | null);
  };
  "Devtools.Ping": {
    req: Record<string, never>;
    res: (types.PingResponse | null);
  };
  "Devtools.Status": {
    req: (types.StatusRequest | null);
    res: (types.StatusResponse | null);
  };
}

const metadata = {
  "Devtools.Info": { path: "/Devtools/Info", primitive: "query" },
  "Devtools.Ping": { path: "/Devtools/Ping", primitive: "query" },
  "Devtools.Status": { path: "/Devtools/Status", primitive: "query" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
