// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "Devtools.Info": {
    req: types.InfoRequest;
    res: types.InfoResponse;
  };
  "Devtools.Ping": {
    req: types.PingRequest;
    res: types.PingResponse;
  };
  "Devtools.Status": {
    req: types.StatusRequest;
    res: types.StatusResponse;
  };
}

const metadata = {
  "Devtools.Info": { method: "GET", path: "/Devtools/Info" },
  "Devtools.Ping": { method: "GET", path: "/Devtools/Ping" },
  "Devtools.Status": { method: "GET", path: "/Devtools/Status" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
