// Code generated by tygor. DO NOT EDIT.

/** InfoRequest is the request for Devtools.Info. */
export interface InfoRequest {
}
/** InfoResponse provides runtime information about the server. */
export interface InfoResponse {
  port: number /* int */;
  version: string;
  num_goroutines: number /* int */;
  num_cpu: number /* int */;
  memory: MemoryStats;
}
/** MemoryStats contains memory statistics. */
export interface MemoryStats {
  alloc: number /* uint64 */;
  total_alloc: number /* uint64 */;
  sys: number /* uint64 */;
  num_gc: number /* uint32 */;
}
/** PingRequest is the request for Devtools.Ping. */
export interface PingRequest {
}
/** PingResponse is the response for Devtools.Ping. */
export interface PingResponse {
  ok: boolean;
}
/** StatusRequest is the request for Devtools.Status. */
export interface StatusRequest {
  /** Initial should be true on first request to receive one-time data. */
  initial?: boolean;
}
/** StatusResponse provides server status and service discovery. */
export interface StatusResponse {
  /** OK indicates the server is healthy. */
  ok: boolean;
  /** Port is the server's listening port. */
  port: number /* int */;
  /** Services maps service names to their method names. */
  services?: Record<string, string[]>;
  /** RawrData contains encoded data blobs. */
  rawrData?: string[];
}
