// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "Tasks.Create": {
    req: types.CreateTaskParams;
    res: types.Task;
  };
  "Tasks.Delete": {
    req: types.DeleteTaskParams;
    res: Record<string, never>;
  };
  "Tasks.Get": {
    req: types.GetTaskParams;
    res: types.Task;
  };
  "Tasks.List": {
    req: types.ListTasksParams;
    res: types.Task[];
  };
  "Tasks.ListIncomplete": {
    req: Record<string, never>;
    res: types.Task[];
  };
  "Tasks.Update": {
    req: types.UpdateTaskParams;
    res: types.Task;
  };
  "Tasks.Version": {
    req: Record<string, never>;
    res: types.Version;
    primitive: "atom";
  };
}

const metadata = {
  "Tasks.Create": { path: "/Tasks/Create", primitive: "exec" },
  "Tasks.Delete": { path: "/Tasks/Delete", primitive: "exec" },
  "Tasks.Get": { path: "/Tasks/Get", primitive: "query" },
  "Tasks.List": { path: "/Tasks/List", primitive: "query" },
  "Tasks.ListIncomplete": { path: "/Tasks/ListIncomplete", primitive: "query" },
  "Tasks.Update": { path: "/Tasks/Update", primitive: "exec" },
  "Tasks.Version": { path: "/Tasks/Version", primitive: "atom" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
