// Code generated by tygor. DO NOT EDIT.

import { z } from 'zod';

export const CreateTaskParamsSchema = z.object({
  title: z.string().min(3), // validate:"min=3"
  description: z.string().nullable(),
});

export const DeleteTaskParamsSchema = z.object({
  id: z.number().int(), // int
});

export const GetTaskParamsSchema = z.object({
  id: z.number().int(), // int
});

export const ListTasksParamsSchema = z.object({
  limit: z.number().int(), // int
  offset: z.number().int(), // int
});

export const TaskSchema = z.object({
  id: z.number().int(), // int
  title: z.string(),
  description: z.string().nullable(),
  completed: z.number().int(), // int
  created_at: z.string(),
  updated_at: z.string(),
});

export const UpdateTaskParamsSchema = z.object({
  title: z.string(),
  description: z.string().nullable(),
  completed: z.number().int(), // int
  id: z.number().int(), // int
});

export const VersionSchema = z.object({
  value: z.number().int(), // int
});

