// Code generated by tygor. DO NOT EDIT.

import { z } from 'zod';
import * as s from './schemas.zod';

export const schemaMap = {
  "Tasks.Create": {
    request: s.CreateTaskParamsSchema,
    response: s.TaskSchema,
  },
  "Tasks.Delete": {
    request: s.DeleteTaskParamsSchema,
    response: z.object({}).strict(),
  },
  "Tasks.Get": {
    request: s.GetTaskParamsSchema,
    response: s.TaskSchema,
  },
  "Tasks.List": {
    request: s.ListTasksParamsSchema,
    response: z.array(s.TaskSchema),
  },
  "Tasks.ListIncomplete": {
    request: z.object({}),
    response: z.array(s.TaskSchema),
  },
  "Tasks.Update": {
    request: s.UpdateTaskParamsSchema,
    response: s.TaskSchema,
  },
  "Tasks.Version": {
    request: z.object({}),
    response: s.VersionSchema,
  },
} as const;

export type SchemaMap = typeof schemaMap;
