// Code generated by tygor. DO NOT EDIT.

/** @see github.com/broady/tygor/examples/with-sqlc/queries/models.go#Task */
export interface Task {
  id: number /* int */;
  title: string;
  description?: string;
  completed: number /* int */;
  created_at: string;
  updated_at: string;
}
/** @see github.com/broady/tygor/examples/with-sqlc/queries/queries.sql.go#UpdateTaskParams */
export interface UpdateTaskParams {
  title: string;
  description?: string;
  completed: number /* int */;
  id: number /* int */;
}
