// Code generated by tygor. DO NOT EDIT.

/** @see main/main.go#CreateTaskParams */
export interface CreateTaskParams {
  title: string;
  description?: string;
}
/** @see main/main.go#DeleteTaskParams */
export interface DeleteTaskParams {
  id: number /* int */;
}
/** @see main/main.go#GetTaskParams */
export interface GetTaskParams {
  id: number /* int */;
}
/** @see main/main.go#ListTasksParams */
export interface ListTasksParams {
  limit: number /* int */;
  offset: number /* int */;
}
/** @see main/main.go#Version */
export interface Version {
  value: number /* int */;
}
