// Code generated by tygor. DO NOT EDIT.
import * as types from './types';

export interface RPCManifest {
  "Comments.Create": {
    req: types.CreateCommentRequest;
    res: types.Comment;
    method: "POST";
    path: "/Comments/Create";
  };
  "Comments.List": {
    req: types.ListCommentsParams;
    res: types.Comment[];
    method: "GET";
    path: "/Comments/List";
  };
  "Posts.Create": {
    req: types.CreatePostRequest;
    res: types.Post;
    method: "POST";
    path: "/Posts/Create";
  };
  "Posts.Get": {
    req: types.GetPostParams;
    res: types.Post;
    method: "GET";
    path: "/Posts/Get";
  };
  "Posts.List": {
    req: types.ListPostsParams;
    res: types.Post[];
    method: "GET";
    path: "/Posts/List";
  };
  "Posts.Publish": {
    req: types.PublishPostRequest;
    res: types.Post;
    method: "POST";
    path: "/Posts/Publish";
  };
  "Posts.Update": {
    req: types.UpdatePostRequest;
    res: types.Post;
    method: "POST";
    path: "/Posts/Update";
  };
  "Users.Create": {
    req: types.CreateUserRequest;
    res: types.User;
    method: "POST";
    path: "/Users/Create";
  };
  "Users.Login": {
    req: types.LoginRequest;
    res: types.LoginResponse;
    method: "POST";
    path: "/Users/Login";
  };
}

export const RPCMetadata = {
  "Comments.Create": { method: "POST", path: "/Comments/Create" },
  "Comments.List": { method: "GET", path: "/Comments/List" },
  "Posts.Create": { method: "POST", path: "/Posts/Create" },
  "Posts.Get": { method: "GET", path: "/Posts/Get" },
  "Posts.List": { method: "GET", path: "/Posts/List" },
  "Posts.Publish": { method: "POST", path: "/Posts/Publish" },
  "Posts.Update": { method: "POST", path: "/Posts/Update" },
  "Users.Create": { method: "POST", path: "/Users/Create" },
  "Users.Login": { method: "POST", path: "/Users/Login" },
} as const;
