// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "Devtools.Info": {
    req: types.InfoRequest;
    res: types.InfoResponse;
  };
  "Devtools.Ping": {
    req: types.PingRequest;
    res: types.PingResponse;
  };
  "Devtools.Status": {
    req: types.StatusRequest;
    res: types.StatusResponse;
  };
  "System.Kill": {
    req: unknown;
    res: unknown;
  };
  "Tasks.Create": {
    req: types.CreateTaskParams;
    res: types.Task;
  };
  "Tasks.List": {
    req: types.ListTasksParams;
    res: types.Task[];
  };
  "Tasks.Toggle": {
    req: types.ToggleTaskParams;
    res: types.Task;
  };
}

const metadata = {
  "Devtools.Info": { method: "GET", path: "/Devtools/Info" },
  "Devtools.Ping": { method: "GET", path: "/Devtools/Ping" },
  "Devtools.Status": { method: "GET", path: "/Devtools/Status" },
  "System.Kill": { method: "POST", path: "/System/Kill" },
  "Tasks.Create": { method: "POST", path: "/Tasks/Create" },
  "Tasks.List": { method: "GET", path: "/Tasks/List" },
  "Tasks.Toggle": { method: "POST", path: "/Tasks/Toggle" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
