// Code generated by tygor. DO NOT EDIT.

/** DescribeRequest is the request for Discovery.Describe. */
export interface DescribeRequest {
}
/**
 * DescribeResponse wraps the discovery document.
 * The Schema field contains the full IR schema as generated by tygorgen.
 */
export interface DescribeResponse {
  /**
 * Schema is the raw JSON schema document.
 * Parse this as the IR schema structure for full type introspection.
 */
  schema: unknown;
}
