// Code generated by tygor. DO NOT EDIT.
import * as types from './types';

export interface RPCManifest {
  "News.Create": {
    req: types.CreateNewsParams;
    res: types.News;
    method: "POST";
    path: "/News/Create";
  };
  "News.List": {
    req: types.ListNewsParams;
    res: types.News[];
    method: "GET";
    path: "/News/List";
  };
}

export const RPCMetadata = {
  "News.Create": { method: "POST", path: "/News/Create" },
  "News.List": { method: "GET", path: "/News/List" },
} as const;
