// Code generated by tygo. DO NOT EDIT.
// Branded types for enhanced type safety
export type DateTime = string & { readonly __brand: 'DateTime' };

// DateTime helper functions
export const DateTime = {
  // Create DateTime from string (assumes valid ISO 8601)
  from: (s: string): DateTime => s as DateTime,

  // Get current timestamp as DateTime
  now: (): DateTime => new Date().toISOString() as DateTime,

  // Parse DateTime to Date object
  toDate: (dt: DateTime): Date => new Date(dt),

  // Format DateTime for display
  format: (dt: DateTime, locale = 'en-US'): string => {
    return new Date(dt).toLocaleString(locale);
  },
};

//////////
// source: types.go

/**
 * NewsStatus represents the publication status of a news article.
 */
/**
 * NewsStatusDraft indicates the article is not yet published.
 */
export const NewsStatusDraft = "draft";
/**
 * NewsStatusPublished indicates the article is publicly visible.
 */
export const NewsStatusPublished = "published";
/**
 * NewsStatusArchived indicates the article has been archived.
 */
export const NewsStatusArchived = "archived";
export type NewsStatus = typeof NewsStatusDraft | typeof NewsStatusPublished | typeof NewsStatusArchived;
/**
 * News represents a news article in the system.
 */
export interface News {
  /**
   * ID is the unique identifier for the article.
   */
  id: number /* int32 */;
  /**
   * Title is the article headline.
   */
  title: string;
  /**
   * Body is the optional article content.
   */
  body?: string;
  /**
   * Status is the current publication status of the article.
   */
  status: NewsStatus;
  /**
   * CreatedAt is the timestamp when the article was created.
   */
  created_at?: DateTime;
}
/**
 * ListNewsParams contains pagination parameters for listing news articles.
 */
export interface ListNewsParams {
  /**
   * Limit is the maximum number of articles to return.
   */
  limit?: number /* int32 */;
  /**
   * Offset is the number of articles to skip.
   */
  offset?: number /* int32 */;
}
/**
 * CreateNewsParams contains the parameters for creating a new news article.
 */
export interface CreateNewsParams {
  /**
   * Title is the article headline (required, 3-100 characters).
   */
  title: string;
  /**
   * Body is the optional article content.
   */
  body?: string;
}
