// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "Tasks.Create": {
    req: types.CreateTaskRequest;
    res: types.Task;
  };
  "Tasks.List": {
    req: types.ListTasksParams;
    res: types.Task[];
  };
}

const metadata = {
  "Tasks.Create": { path: "/Tasks/Create", primitive: "exec" },
  "Tasks.List": { path: "/Tasks/List", primitive: "query" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
