// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "Devtools.GetDiscovery": {
    req: Record<string, never>;
    res: types.GetDiscoveryResponse;
  };
  "Devtools.GetSource": {
    req: types.GetSourceRequest;
    res: types.GetSourceResponse;
  };
  "Devtools.GetStatus": {
    req: Record<string, never>;
    res: types.GetStatusResponse;
  };
  "Devtools.Reload": {
    req: types.ReloadRequest;
    res: Record<string, never>;
  };
  "Devtools.UpdateStatus": {
    req: types.UpdateStatusRequest;
    res: Record<string, never>;
  };
}

const metadata = {
  "Devtools.GetDiscovery": { path: "/Devtools/GetDiscovery", primitive: "query" },
  "Devtools.GetSource": { path: "/Devtools/GetSource", primitive: "query" },
  "Devtools.GetStatus": { path: "/Devtools/GetStatus", primitive: "query" },
  "Devtools.Reload": { path: "/Devtools/Reload", primitive: "exec" },
  "Devtools.UpdateStatus": { path: "/Devtools/UpdateStatus", primitive: "exec" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
