// Code generated by tygor. DO NOT EDIT.

/** AppStatus represents the status of the user's app as reported by vite plugin. */
export interface AppStatus {
  status: string;
  port?: number /* int */;
  error?: string;
  phase?: string;
}
/** DevtoolsStatus is the status of the devtools server itself. */
export interface DevtoolsStatus {
  status: string;
  version: string;
}
/** GetDiscoveryRequest is the request for Devtools.GetDiscovery. */
export interface GetDiscoveryRequest {
}
/** GetDiscoveryResponse returns the discovery.json content. */
export interface GetDiscoveryResponse {
  /** Discovery is the raw discovery.json content as a JSON object. */
  discovery: unknown;
}
/** GetSourceRequest is the request for Devtools.GetSource. */
export interface GetSourceRequest {
  file: string;
  line?: number /* int */;
  context?: number /* int */;
}
/** GetSourceResponse returns source code with context. */
export interface GetSourceResponse {
  file: string;
  language: string;
  lines?: SourceLine[];
  context: number /* int */;
}
/** GetStatusRequest is the request for Devtools.GetStatus. */
export interface GetStatusRequest {
}
/** GetStatusResponse returns the combined devtools status. */
export interface GetStatusResponse {
  devtools: DevtoolsStatus;
  app?: AppStatus;
}
/** ReloadRequest triggers a reload of discovery.json. */
export interface ReloadRequest {
  files?: string[];
  reason?: string;
}
/** ReloadResponse is the response for Reload. */
export interface ReloadResponse {
}
/** SourceLine represents a single line of source code. */
export interface SourceLine {
  num: number /* int */;
  content: string;
  highlight?: boolean;
}
/** UpdateStatusRequest is sent by vite plugin to update app status. */
export interface UpdateStatusRequest {
  app: AppStatus;
}
/** UpdateStatusResponse is the response for UpdateStatus. */
export interface UpdateStatusResponse {
}
