// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "Posts.Create": {
    req: types.api_CreatePostParams;
    res: types.api_Result_github_com_broady_tygor_examples_reflection_api_Post;
  };
  "Users.Get": {
    req: types.api_GetUserParams;
    res: types.api_Result_github_com_broady_tygor_examples_reflection_api_User;
  };
  "Users.List": {
    req: types.api_ListUsersParams;
    res: types.api_PagedResponse_github_com_broady_tygor_examples_reflection_api_User;
  };
}

const metadata = {
  "Posts.Create": { path: "/Posts/Create", primitive: "exec" },
  "Users.Get": { path: "/Users/Get", primitive: "query" },
  "Users.List": { path: "/Users/List", primitive: "query" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
