// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "Migration.Migrate": {
    req: types.MigrationRequest;
    res: types.MigrationResponse;
  };
  "V1Users.Get": {
    req: types.v1_GetUserRequest;
    res: types.v1_User;
  };
  "V2Users.Get": {
    req: types.v2_GetUserRequest;
    res: types.v2_User;
  };
}

const metadata = {
  "Migration.Migrate": { path: "/Migration/Migrate", primitive: "exec" },
  "V1Users.Get": { path: "/V1Users/Get", primitive: "query" },
  "V2Users.Get": { path: "/V2Users/Get", primitive: "query" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
