// Code generated by tygor. DO NOT EDIT.

/** GetUserRequest is the request for getting a v1 user. */
export interface v1_GetUserRequest {
  id: number;
}
/** GetUserRequest is the request for getting a v2 user. */
export interface v2_GetUserRequest {
  id: number;
}
/**
 * MigrationRequest demonstrates referencing same-named types from different packages.
 * Without StripPackagePrefix, both User types would collide as "User" in TypeScript.
 * With StripPackagePrefix, they become "v1_User" and "v2_User".
 */
export interface MigrationRequest {
  v1_user: v1_User;
  v2_user: v2_User;
}
/** MigrationResponse returns both user versions. */
export interface MigrationResponse {
  success: boolean;
  v1_user: v1_User;
  v2_user: v2_User;
}
/** User represents a user in v1 API. */
export interface v1_User {
  id: number;
  name: string;
}
/** User represents a user in v2 API with additional fields. */
export interface v2_User {
  id: number;
  name: string;
  email: string;
  created_at: string;
}
