// Code generated by tygor. DO NOT EDIT.

/**
 * GetUserRequest is the request for getting a v1 user.
 * @see github.com/broady/tygor/examples/multipackage/api/v1/types.go#GetUserRequest
 */
export interface v1_GetUserRequest {
  id: number /* int64 */;
}
/**
 * GetUserRequest is the request for getting a v2 user.
 * @see github.com/broady/tygor/examples/multipackage/api/v2/types.go#GetUserRequest
 */
export interface v2_GetUserRequest {
  id: number /* int64 */;
}
/**
 * MigrationRequest demonstrates referencing same-named types from different packages.
 * Without StripPackagePrefix, both User types would collide as "User" in TypeScript.
 * With StripPackagePrefix, they become "v1_User" and "v2_User".
 * @see github.com/broady/tygor/examples/multipackage/api/types.go#MigrationRequest
 */
export interface MigrationRequest {
  v1_user: v1_User;
  v2_user: v2_User;
}
/**
 * MigrationResponse returns both user versions.
 * @see github.com/broady/tygor/examples/multipackage/api/types.go#MigrationResponse
 */
export interface MigrationResponse {
  success: boolean;
  v1_user: v1_User;
  v2_user: v2_User;
}
/**
 * User represents a user in v1 API.
 * @see github.com/broady/tygor/examples/multipackage/api/v1/types.go#User
 */
export interface v1_User {
  id: number /* int64 */;
  name: string;
}
/**
 * User represents a user in v2 API with additional fields.
 * @see github.com/broady/tygor/examples/multipackage/api/v2/types.go#User
 */
export interface v2_User {
  id: number /* int64 */;
  name: string;
  email: string;
  created_at: string;
}
