// Code generated by tygor. DO NOT EDIT.

/** CreateTaskRequest contains the data needed to create a new task. */
export interface CreateTaskRequest {
  title: string;
  description?: string;
  priority: Priority;
  assignee?: string;
  tags?: string[];
}
/** ListTasksParams contains query parameters for listing tasks. */
export interface ListTasksParams {
  /** Status filters tasks by their current status. */
  status?: Status;
  /** Assignee filters tasks by assigned user. */
  assignee?: string;
  /** Limit is the maximum number of results. */
  limit?: number;
  /** Offset is the pagination offset. */
  offset?: number;
}
/** Priority represents task urgency levels. */
export type Priority = 4 | 3 | 1 | 2;
/** Status represents the state of a task. */
export type Status = "cancelled" | "completed" | "in_progress" | "pending";
/** Task represents a work item in the system. */
export interface Task {
  /** ID is the unique identifier for the task. */
  id: string;
  /** Title is the task's headline. */
  title: string;
  /** Description is the detailed task description. */
  description?: string;
  /** Status is the current state of the task. */
  status: Status;
  /** Priority determines the task's urgency. */
  priority: Priority;
  /** Assignee is the user responsible for the task. */
  assignee?: string;
  /** DueDate is when the task should be completed. */
  due_date?: string;
  /** Tags are labels for categorization. */
  tags?: string[];
  /** CreatedAt is when the task was created. */
  created_at: string;
}
