// Code generated by tygor. DO NOT EDIT.
import { ServiceRegistry } from '@tygor/client';
import * as types from './types';

export interface RPCManifest {
  "Items.Create": {
    req: types.CreateItemRequest;
    res: types.Item;
  };
  "Items.Get": {
    req: types.GetItemRequest;
    res: types.Item;
  };
  "Items.List": {
    req: types.ListItemsRequest;
    res: types.ListItemsResponse;
  };
}

const metadata = {
  "Items.Create": { method: "POST", path: "/Items/Create" },
  "Items.Get": { method: "GET", path: "/Items/Get" },
  "Items.List": { method: "GET", path: "/Items/List" },
} as const;

export const registry: ServiceRegistry<RPCManifest> = {
  manifest: {} as RPCManifest,
  metadata,
};
