// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "Items.Create": {
    req: types.CreateItemRequest;
    res: types.Item;
  };
  "Items.Get": {
    req: types.GetItemRequest;
    res: types.Item;
  };
  "Items.List": {
    req: types.ListItemsRequest;
    res: types.ListItemsResponse;
  };
}

const metadata = {
  "Items.Create": { path: "/Items/Create", primitive: "exec" },
  "Items.Get": { path: "/Items/Get", primitive: "query" },
  "Items.List": { path: "/Items/List", primitive: "query" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
