// Code generated by tygor. DO NOT EDIT.

import { z } from 'zod';
import * as s from './schemas.zod';

export const schemaMap = {
  "Items.Create": {
    request: s.CreateItemRequestSchema,
    response: s.ItemSchema,
  },
  "Items.Get": {
    request: s.GetItemRequestSchema,
    response: s.ItemSchema,
  },
  "Items.List": {
    request: s.ListItemsRequestSchema,
    response: s.ListItemsResponseSchema,
  },
} as const;

export type SchemaMap = typeof schemaMap;
