// Code generated by tygor. DO NOT EDIT.

import { z } from 'zod';

export const CreateItemRequestSchema = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  price_cents: z.number().int().min(-9007199254740991).max(9007199254740991).optional(), // int64
  tags: z.array(z.string()).optional(),
});

export const GetItemRequestSchema = z.object({
  id: z.number().int().min(-9007199254740991).max(9007199254740991).optional(), // int64
});

export const ItemSchema = z.object({
  id: z.number().int().min(-9007199254740991).max(9007199254740991).optional(), // int64
  name: z.string().optional(),
  description: z.string().optional(),
  price_cents: z.number().int().min(-9007199254740991).max(9007199254740991).optional(), // int64
  tags: z.array(z.string()).optional(),
});

export const ListItemsRequestSchema = z.object({
  limit: z.number().int().min(-2147483648).max(2147483647).optional(), // int32
  offset: z.number().int().min(-2147483648).max(2147483647).optional(), // int32
});

export const ListItemsResponseSchema = z.object({
  items: z.array(ItemSchema.nullable()).optional(),
  total: z.number().int().min(-2147483648).max(2147483647).optional(), // int32
});

