// Code generated by tygor. DO NOT EDIT.

export interface CreateItemRequest {
  name?: string;
  description?: string;
  price_cents?: number;
  tags?: string[];
}
export interface GetItemRequest {
  id?: number;
}
export interface Item {
  id?: number;
  name?: string;
  description?: string;
  price_cents?: number;
  tags?: string[];
}
export interface ListItemsRequest {
  limit?: number;
  offset?: number;
}
export interface ListItemsResponse {
  items?: Item[];
  total?: number;
}
