// Code generated by tygor. DO NOT EDIT.

/** CreateItemRequest is the request to create an item. */
export interface CreateItemRequest {
  name?: string;
  description?: string;
  price_cents?: number;
  tags?: string[];
}
/** GetItemRequest is the request to get an item by ID. */
export interface GetItemRequest {
  id?: number;
}
/** Item represents an item in the catalog. */
export interface Item {
  id?: number;
  name?: string;
  description?: string;
  price_cents?: number;
  tags?: string[];
}
/** ListItemsRequest is the request to list items. */
export interface ListItemsRequest {
  limit?: number;
  offset?: number;
}
/** ListItemsResponse contains a list of items. */
export interface ListItemsResponse {
  items?: Item[];
  total?: number;
}
