// Code generated by tygo. DO NOT EDIT.

//////////
// source: messages.pb.go

/**
 * CreateItemRequest is the request to create an item.
 */
export interface CreateItemRequest {
  name?: string;
  description?: string;
  price_cents?: number /* int64 */;
  tags?: string[];
}
/**
 * Item represents an item in the catalog.
 */
export interface Item {
  id?: number /* int64 */;
  name?: string;
  description?: string;
  price_cents?: number /* int64 */;
  tags?: string[];
}
/**
 * ListItemsRequest is the request to list items.
 */
export interface ListItemsRequest {
  limit?: number /* int32 */;
  offset?: number /* int32 */;
}
/**
 * ListItemsResponse contains a list of items.
 */
export interface ListItemsResponse {
  items?: (Item | undefined)[];
  total?: number /* int32 */;
}
/**
 * GetItemRequest is the request to get an item by ID.
 */
export interface GetItemRequest {
  id?: number /* int64 */;
}
