// Code generated by tygor. DO NOT EDIT.

/** @see github.com/broady/tygor/examples/config-showcase/api/types.go#CreateTaskRequest */
export interface CreateTaskRequest {
  title: string;
  description?: string;
  priority: Priority;
  assignee?: string;
  tags?: string[];
}
/** @see github.com/broady/tygor/examples/config-showcase/api/types.go#ListTasksParams */
export interface ListTasksParams {
  status?: Status;
  assignee?: string;
  limit?: number /* int */;
  offset?: number /* int */;
}
/** @see github.com/broady/tygor/examples/config-showcase/api/types.go#Priority */
export type Priority = 4 | 3 | 1 | 2;
/** @see github.com/broady/tygor/examples/config-showcase/api/types.go#Status */
export type Status = "cancelled" | "completed" | "in_progress" | "pending";
/** @see github.com/broady/tygor/examples/config-showcase/api/types.go#Task */
export interface Task {
  id: string;
  title: string;
  description?: string;
  status: Status;
  priority: Priority;
  assignee?: string;
  due_date?: string /* RFC3339 */;
  tags?: string[];
  created_at: string /* RFC3339 */;
}
