// Code generated by tygor. DO NOT EDIT.

export interface CreateTaskRequest {
  title: string;
  description?: string;
  priority: Priority;
  assignee?: string;
  tags?: string[];
}
export interface ListTasksParams {
  status?: Status;
  assignee?: string;
  limit?: number;
  offset?: number;
}
export type Priority = 4 | 3 | 1 | 2;
export type Status = "cancelled" | "completed" | "in_progress" | "pending";
export interface Task {
  id: string;
  title: string;
  description?: string;
  status: Status;
  priority: Priority;
  assignee?: string;
  due_date?: string;
  tags?: string[];
  created_at: string;
}
