// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "Tasks.Create": {
    req: types.CreateTaskRequest;
    res: types.Task;
  };
  "Tasks.Get": {
    req: types.GetTaskParams;
    res: types.Task;
  };
  "Tasks.List": {
    req: types.ListParams;
    res: types.Task[];
  };
  "Tasks.Update": {
    req: types.UpdateTaskRequest;
    res: types.Task;
  };
  "Users.Create": {
    req: types.CreateUserRequest;
    res: types.User;
  };
  "Users.List": {
    req: types.ListParams;
    res: types.User[];
  };
}

const metadata = {
  "Tasks.Create": { method: "POST", path: "/Tasks/Create" },
  "Tasks.Get": { method: "GET", path: "/Tasks/Get" },
  "Tasks.List": { method: "GET", path: "/Tasks/List" },
  "Tasks.Update": { method: "POST", path: "/Tasks/Update" },
  "Users.Create": { method: "POST", path: "/Users/Create" },
  "Users.List": { method: "GET", path: "/Users/List" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
