// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "Tasks.Create": {
    req: types.CreateTaskRequest;
    res: types.Task;
  };
  "Tasks.Get": {
    req: types.GetTaskParams;
    res: types.Task;
  };
  "Tasks.List": {
    req: types.ListParams;
    res: types.Task[];
  };
  "Tasks.Update": {
    req: types.UpdateTaskRequest;
    res: types.Task;
  };
  "Users.Create": {
    req: types.CreateUserRequest;
    res: types.User;
  };
  "Users.List": {
    req: types.ListParams;
    res: types.User[];
  };
}

const metadata = {
  "Tasks.Create": { path: "/Tasks/Create", primitive: "exec" },
  "Tasks.Get": { path: "/Tasks/Get", primitive: "query" },
  "Tasks.List": { path: "/Tasks/List", primitive: "query" },
  "Tasks.Update": { path: "/Tasks/Update", primitive: "exec" },
  "Users.Create": { path: "/Users/Create", primitive: "exec" },
  "Users.List": { path: "/Users/List", primitive: "query" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
