// Code generated by tygor. DO NOT EDIT.

import { z } from 'zod';
import * as s from './schemas.zod';

export const schemaMap = {
  "Tasks.Create": {
    input: s.CreateTaskRequestSchema,
    output: s.TaskSchema,
  },
  "Tasks.Get": {
    input: s.GetTaskParamsSchema,
    output: s.TaskSchema,
  },
  "Tasks.List": {
    input: s.ListParamsSchema,
    output: z.array(s.TaskSchema),
  },
  "Tasks.Update": {
    input: s.UpdateTaskRequestSchema,
    output: s.TaskSchema,
  },
  "Users.Create": {
    input: s.CreateUserRequestSchema,
    output: s.UserSchema,
  },
  "Users.List": {
    input: s.ListParamsSchema,
    output: z.array(s.UserSchema),
  },
} as const;

export type SchemaMap = typeof schemaMap;
