// Code generated by tygor. DO NOT EDIT.

import * as z from 'zod/mini';

export const CreateTaskRequestSchema = z.object({
  title: z.string().check(z.minLength(1), z.minLength(1), z.maxLength(200)), // validate:"required,min=1,max=200"
  description: z.optional(z.nullable(z.string().check(z.maxLength(2000)))), // validate:"omitempty,max=2000"
  priority: z.enum(["low", "medium", "high", "critical"]),
  assignee_id: z.optional(z.nullable(z.number().check(z.int(), z.gte(-9007199254740991), z.lte(9007199254740991)).check(z.gt(0)))), // int64 validate:"omitempty,gt=0"
  tags: z.array(z.string()).check(z.maxLength(10)), // validate:"max=10"
});

export const CreateUserRequestSchema = z.object({
  username: z.string().check(z.minLength(1), z.minLength(3), z.maxLength(20), z.regex(/^[a-zA-Z0-9]+$/)), // validate:"required,min=3,max=20,alphanum"
  email: z.string().check(z.minLength(1), z.email()), // validate:"required,email"
  password: z.string().check(z.minLength(1), z.minLength(8), z.maxLength(72)), // validate:"required,min=8,max=72"
  website: z.optional(z.nullable(z.string().check(z.url()))), // validate:"omitempty,url"
  age: z.optional(z.nullable(z.number().check(z.int(), z.gte(-2147483648), z.lte(2147483647)).check(z.gte(13), z.lte(150)))), // int32 validate:"omitempty,gte=13,lte=150"
});

export const GetTaskParamsSchema = z.object({
  task_id: z.number().check(z.int(), z.gte(-9007199254740991), z.lte(9007199254740991)).check(z.gt(0)), // int64 validate:"required,gt=0"
});

export const ListParamsSchema = z.object({
  limit: z.number().check(z.int(), z.gte(-2147483648), z.lte(2147483647)).check(z.gte(1), z.lte(100)), // int32 validate:"gte=1,lte=100"
  offset: z.number().check(z.int(), z.gte(-2147483648), z.lte(2147483647)).check(z.gte(0)), // int32 validate:"gte=0"
});

export const TaskSchema = z.object({
  id: z.number().check(z.int(), z.gte(-9007199254740991), z.lte(9007199254740991)), // int64
  title: z.string().check(z.minLength(1), z.minLength(1), z.maxLength(200)), // validate:"required,min=1,max=200"
  description: z.optional(z.nullable(z.string().check(z.maxLength(2000)))), // validate:"omitempty,max=2000"
  priority: z.enum(["low", "medium", "high", "critical"]),
  assignee_id: z.optional(z.nullable(z.number().check(z.int(), z.gte(-9007199254740991), z.lte(9007199254740991)).check(z.gt(0)))), // int64 validate:"omitempty,gt=0"
  tags: z.array(z.string()).check(z.maxLength(10)), // validate:"max=10"
  due_date: z.optional(z.nullable(z.string().check(z.iso.datetime()))),
  completed: z.boolean(),
});

export const UpdateTaskRequestSchema = z.object({
  task_id: z.number().check(z.int(), z.gte(-9007199254740991), z.lte(9007199254740991)).check(z.gt(0)), // int64 validate:"required,gt=0"
  title: z.optional(z.nullable(z.string().check(z.minLength(1), z.maxLength(200)))), // validate:"omitempty,min=1,max=200"
  description: z.optional(z.nullable(z.string().check(z.maxLength(2000)))), // validate:"omitempty,max=2000"
  priority: z.optional(z.enum(["low", "medium", "high", "critical"])),
  assignee_id: z.optional(z.nullable(z.number().check(z.int(), z.gte(-9007199254740991), z.lte(9007199254740991)).check(z.gt(0)))), // int64 validate:"omitempty,gt=0"
  completed: z.optional(z.nullable(z.boolean())),
});

export const UserSchema = z.object({
  id: z.number().check(z.int(), z.gte(-9007199254740991), z.lte(9007199254740991)), // int64
  username: z.string().check(z.minLength(1), z.minLength(3), z.maxLength(20), z.regex(/^[a-zA-Z0-9]+$/)), // validate:"required,min=3,max=20,alphanum"
  email: z.string().check(z.minLength(1), z.email()), // validate:"required,email"
  website: z.optional(z.nullable(z.string().check(z.url()))), // validate:"omitempty,url"
  age: z.optional(z.nullable(z.number().check(z.int(), z.gte(-2147483648), z.lte(2147483647)).check(z.gte(0), z.lte(150)))), // int32 validate:"omitempty,gte=0,lte=150"
  created_at: z.string().check(z.iso.datetime()),
});

