// Code generated by tygor. DO NOT EDIT.

import { z } from 'zod';
import * as s from './schemas.zod';

export const schemaMap = {
  "Tasks.Create": {
    request: s.CreateTaskRequestSchema,
    response: s.TaskSchema,
  },
  "Tasks.Get": {
    request: s.GetTaskParamsSchema,
    response: s.TaskSchema,
  },
  "Tasks.List": {
    request: s.ListParamsSchema,
    response: z.array(s.TaskSchema.nullable()),
  },
  "Tasks.Update": {
    request: s.UpdateTaskRequestSchema,
    response: s.TaskSchema,
  },
  "Users.Create": {
    request: s.CreateUserRequestSchema,
    response: s.UserSchema,
  },
  "Users.List": {
    request: s.ListParamsSchema,
    response: z.array(s.UserSchema.nullable()),
  },
} as const;

export type SchemaMap = typeof schemaMap;
