// Code generated by tygor. DO NOT EDIT.

/**
 * CreateTaskRequest demonstrates complex request validation.
 * @see github.com/broady/tygor/examples/zod/api/types.go#CreateTaskRequest
 */
export interface CreateTaskRequest {
  title: string;
  description?: string;
  priority: string;
  assignee_id?: number /* int64 */;
  tags?: string[];
}
/**
 * CreateUserRequest demonstrates request validation.
 * @see github.com/broady/tygor/examples/zod/api/types.go#CreateUserRequest
 */
export interface CreateUserRequest {
  username: string;
  email: string;
  password: string;
  website?: string;
  age?: number /* int32 */;
}
/**
 * GetTaskParams contains parameters for getting a task.
 * @see github.com/broady/tygor/examples/zod/api/types.go#GetTaskParams
 */
export interface GetTaskParams {
  task_id: number /* int64 */;
}
/**
 * ListParams contains pagination parameters.
 * @see github.com/broady/tygor/examples/zod/api/types.go#ListParams
 */
export interface ListParams {
  limit: number /* int32 */;
  offset: number /* int32 */;
}
/**
 * Task demonstrates nested types and oneof validation.
 * @see github.com/broady/tygor/examples/zod/api/types.go#Task
 */
export interface Task {
  id: number /* int64 */;
  title: string;
  description?: string;
  priority: string;
  assignee_id?: number /* int64 */;
  tags?: string[];
  due_date?: string /* RFC3339 */;
  completed: boolean;
}
/**
 * UpdateTaskRequest demonstrates partial update patterns.
 * @see github.com/broady/tygor/examples/zod/api/types.go#UpdateTaskRequest
 */
export interface UpdateTaskRequest {
  task_id: number /* int64 */;
  title?: string;
  description?: string;
  priority?: string;
  assignee_id?: number /* int64 */;
  completed?: boolean;
}
/**
 * User demonstrates common validation patterns.
 * @see github.com/broady/tygor/examples/zod/api/types.go#User
 */
export interface User {
  id: number /* int64 */;
  username: string;
  email: string;
  website?: string;
  age?: number /* int32 */;
  created_at: string /* RFC3339 */;
}
