// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "System.Info": {
    req: Record<string, never>;
    res: types.RuntimeInfo;
  };
  "System.InfoStream": {
    req: Record<string, never>;
    res: types.RuntimeInfo;
    primitive: "stream";
  };
  "Tasks.Create": {
    req: types.CreateTaskParams;
    res: types.Task;
  };
  "Tasks.List": {
    req: types.ListTasksParams;
    res: (types.Task | null)[];
  };
  "Tasks.Toggle": {
    req: types.ToggleTaskParams;
    res: types.Task;
  };
}

const metadata = {
  "System.Info": { path: "/System/Info", primitive: "query" },
  "System.InfoStream": { path: "/System/InfoStream", primitive: "stream" },
  "Tasks.Create": { path: "/Tasks/Create", primitive: "exec" },
  "Tasks.List": { path: "/Tasks/List", primitive: "query" },
  "Tasks.Toggle": { path: "/Tasks/Toggle", primitive: "exec" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
