// Code generated by tygor. DO NOT EDIT.

/**
 * CreateTaskParams contains parameters for creating a task.
 * @see github.com/broady/tygor/examples/react/api/types.go#CreateTaskParams
 */
export interface CreateTaskParams {
  title: string;
}
/**
 * ListTasksParams contains parameters for listing tasks.
 * @see github.com/broady/tygor/examples/react/api/types.go#ListTasksParams
 */
export interface ListTasksParams {
  /** ShowDone filters to show completed tasks. */
  show_done?: boolean;
}
/**
 * MemoryStats contains memory allocation statistics.
 * @see github.com/broady/tygor/examples/react/api/types.go#MemoryStats
 */
export interface MemoryStats {
  alloc: number /* uint64 */;
  total_alloc: number /* uint64 */;
  sys: number /* uint64 */;
  num_gc: number /* uint32 */;
}
/**
 * RuntimeInfo contains Go runtime statistics.
 * @see github.com/broady/tygor/examples/react/api/types.go#RuntimeInfo
 */
export interface RuntimeInfo {
  version: string;
  num_goroutines: number /* int */;
  num_cpu: number /* int */;
  memory: MemoryStats;
}
/**
 * Task represents a todo item.
 * @see github.com/broady/tygor/examples/react/api/types.go#Task
 */
export interface Task {
  /** ID is the unique identifier. */
  id: number /* int32 */;
  /** Title is the task description. */
  title: string;
  /** Done indicates if the task is completed. */
  done: boolean;
}
/**
 * ToggleTaskParams identifies which task to toggle.
 * @see github.com/broady/tygor/examples/react/api/types.go#ToggleTaskParams
 */
export interface ToggleTaskParams {
  id: number /* int32 */;
}
