// [snippet:generated-zod]
// Code generated by tygor. DO NOT EDIT.
import { z } from "zod";

export const UserSchema = z.object({
  id: z.number().int(),
  name: z.string(),
  email: z.string().min(1).email(), // validate:"required,email"
});
// [/snippet:generated-zod]
