# Multipackage example - demonstrates StripPackagePrefix for type disambiguation
include ../common.mk

# Override GO_FILES to include v1 and v2 subdirectories
GO_FILES := main.go api/types.go api/v1/types.go api/v2/types.go
TS_FILES := client/index.ts
