// Code generated by tygor. DO NOT EDIT.

/** CreateTaskRequest contains the data needed to create a new task. */
export interface CreateTaskRequest {
  title: string;
  description?: string;
  priority: Priority;
  assignee?: string;
  tags?: string[];
}
/** ListTasksParams contains query parameters for listing tasks. */
export interface ListTasksParams {
  /** Status filters tasks by their current status. */
  status?: Status;
  /** Assignee filters tasks by assigned user. */
  assignee?: string;
  /** Limit is the maximum number of results. */
  limit?: number;
  /** Offset is the pagination offset. */
  offset?: number;
}
/** Priority represents task urgency levels. */
export const enum Priority {
  /** PriorityCritical is for immediate attention. */
  PriorityCritical = 4,
  /** PriorityHigh is for urgent tasks. */
  PriorityHigh = 3,
  /** PriorityLow is for non-urgent tasks. */
  PriorityLow = 1,
  /** PriorityMedium is the default priority. */
  PriorityMedium = 2,
}
/** Status represents the state of a task. */
export const enum Status {
  /** StatusCancelled indicates the task was cancelled. */
  StatusCancelled = "cancelled",
  /** StatusCompleted indicates the task has been finished. */
  StatusCompleted = "completed",
  /** StatusInProgress indicates the task is currently being worked on. */
  StatusInProgress = "in_progress",
  /** StatusPending indicates the task is waiting to be started. */
  StatusPending = "pending",
}
/** Task represents a work item in the system. */
export interface Task {
  /** ID is the unique identifier for the task. */
  id: string;
  /** Title is the task's headline. */
  title: string;
  /** Description is the detailed task description. */
  description?: string;
  /** Status is the current state of the task. */
  status: Status;
  /** Priority determines the task's urgency. */
  priority: Priority;
  /** Assignee is the user responsible for the task. */
  assignee?: string;
  /** DueDate is when the task should be completed. */
  due_date?: string;
  /** Tags are labels for categorization. */
  tags: string[] | null;
  /** CreatedAt is when the task was created. */
  created_at: string;
}
