// Package discovery provides utilities for serving API discovery documents.
//
// The discovery document is generated at build time by tygorgen with WithDiscovery():
//
//	tygorgen.FromApp(app).WithDiscovery().ToDir("./client/src/rpc")
//
// This produces discovery.json and discovery_schema.gen.go files.
//
// Usage (simplest - loads from file at startup):
//
//	discovery.NewFromFile(app, "./client/src/rpc/discovery.json").Register()
//
// Usage (single binary - uses generated Go file):
//
//	import "yourapp/client/src/rpc"
//	discovery.NewFromBytes(app, rpc.DiscoverySchema).Register()
package discovery

import (
	"context"
	"encoding/json"
	"fmt"
	"os"

	"github.com/broady/tygor"
)

// Service serves a pre-generated discovery document.
type Service struct {
	app          *tygor.App
	discoveryDoc json.RawMessage
}

// NewFromFile creates a discovery service that loads the schema from a file.
// This is the simplest setup - just point to your generated discovery.json:
//
//	discovery.NewFromFile(app, "./client/src/rpc/discovery.json").Register()
//
// The file is read once at startup. Returns an error if the file cannot be read.
func NewFromFile(app *tygor.App, path string) (*Service, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("discovery: failed to read %s: %w", path, err)
	}
	return NewFromBytes(app, data), nil
}

// MustFromFile is like NewFromFile but panics on error.
// Useful for simple setups where the file is expected to exist:
//
//	discovery.MustFromFile(app, "./client/src/rpc/discovery.json").Register()
func MustFromFile(app *tygor.App, path string) *Service {
	svc, err := NewFromFile(app, path)
	if err != nil {
		panic(err)
	}
	return svc
}

// NewFromBytes creates a discovery service from JSON bytes.
// Use with the generated discovery_schema.gen.go for single-binary deployment:
//
//	import "yourapp/client/src/rpc"
//	discovery.NewFromBytes(app, rpc.DiscoverySchema).Register()
func NewFromBytes(app *tygor.App, jsonBytes []byte) *Service {
	return &Service{
		app:          app,
		discoveryDoc: json.RawMessage(jsonBytes),
	}
}

// Register adds the discovery service to the app.
func (s *Service) Register() {
	svc := s.app.Service("Discovery")
	svc.Register("Describe", tygor.Query(s.Describe))
}

// DescribeRequest is the request for Discovery.Describe.
type DescribeRequest struct{}

// DescribeResponse wraps the discovery document.
// The Schema field contains the full IR schema as generated by tygorgen.
type DescribeResponse struct {
	// Schema is the raw JSON schema document.
	// Parse this as the IR schema structure for full type introspection.
	Schema any `json:"schema"`
}

// Describe returns the pre-generated discovery document.
func (s *Service) Describe(ctx context.Context, req *DescribeRequest) (*DescribeResponse, error) {
	// Parse the JSON so it serializes as an object, not a string
	var schema any
	if err := json.Unmarshal(s.discoveryDoc, &schema); err != nil {
		return nil, err
	}
	return &DescribeResponse{Schema: schema}, nil
}
