// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "System.Info": {
    req: types.Empty;
    res: types.RuntimeInfo;
  };
  "Tasks.Create": {
    req: types.CreateTaskParams;
    res: types.Task;
  };
  "Tasks.List": {
    req: types.ListTasksParams;
    res: types.Task[];
  };
  "Tasks.Toggle": {
    req: types.ToggleTaskParams;
    res: types.Task;
  };
}

const metadata = {
  "System.Info": { method: "GET", path: "/System/Info" },
  "Tasks.Create": { method: "POST", path: "/Tasks/Create" },
  "Tasks.List": { method: "GET", path: "/Tasks/List" },
  "Tasks.Toggle": { method: "POST", path: "/Tasks/Toggle" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
