// Code generated by tygor. DO NOT EDIT.

import { z } from 'zod';

export const CreateTaskParamsSchema = z.object({
  title: z.string().min(1).min(1), // validate:"required,min=1"
});

export const ListTasksParamsSchema = z.object({
  show_done: z.boolean().nullable().optional(),
});

export const MemoryStatsSchema = z.object({
  alloc: z.number().int().nonnegative().max(9007199254740991), // uint64
  total_alloc: z.number().int().nonnegative().max(9007199254740991), // uint64
  sys: z.number().int().nonnegative().max(9007199254740991), // uint64
  num_gc: z.number().int().nonnegative().max(4294967295), // uint32
});

export const RuntimeInfoSchema = z.object({
  version: z.string(),
  num_goroutines: z.number().int(), // int
  num_cpu: z.number().int(), // int
  memory: MemoryStatsSchema,
});

export const TaskSchema = z.object({
  id: z.number().int().min(-2147483648).max(2147483647), // int32
  title: z.string(),
  done: z.boolean(),
});

export const ToggleTaskParamsSchema = z.object({
  id: z.number().int().min(-2147483648).max(2147483647), // int32 validate:"required"
});

