// Code generated by tygor. DO NOT EDIT.

import { z } from 'zod';
import * as s from './schemas.zod';

export const schemaMap = {
  "System.Info": {
    request: z.object({}),
    response: s.RuntimeInfoSchema,
  },
  "System.InfoStream": {
    request: z.object({}),
    response: s.RuntimeInfoSchema,
  },
  "Tasks.Create": {
    request: s.CreateTaskParamsSchema,
    response: s.TaskSchema,
  },
  "Tasks.List": {
    request: s.ListTasksParamsSchema,
    response: z.array(s.TaskSchema.nullable()),
  },
  "Tasks.Toggle": {
    request: s.ToggleTaskParamsSchema,
    response: s.TaskSchema,
  },
} as const;

export type SchemaMap = typeof schemaMap;
