// Code generated by tygor. DO NOT EDIT.

/** CreateTaskParams contains parameters for creating a task. */
export interface CreateTaskParams {
  title: string;
}
/** ListTasksParams contains parameters for listing tasks. */
export interface ListTasksParams {
  /** ShowDone filters to show completed tasks. */
  show_done?: boolean;
}
/** Task represents a todo item. */
export interface Task {
  /** ID is the unique identifier. */
  id: number /* int32 */;
  /** Title is the task description. */
  title: string;
  /** Done indicates if the task is completed. */
  done: boolean;
}
/** ToggleTaskParams identifies which task to toggle. */
export interface ToggleTaskParams {
  id: number /* int32 */;
}
