// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "Devtools.Info": {
    req: Record<string, never>;
    res: types.InfoResponse;
  };
  "Devtools.Ping": {
    req: Record<string, never>;
    res: types.PingResponse;
  };
  "Devtools.Status": {
    req: types.StatusRequest;
    res: types.StatusResponse;
  };
  "System.Kill": {
    req: Record<string, never>;
    res: Record<string, never>;
  };
  "Tasks.Create": {
    req: types.CreateTaskParams;
    res: types.Task;
  };
  "Tasks.List": {
    req: types.ListTasksParams;
    res: (types.Task | null)[];
  };
  "Tasks.MakeError": {
    req: Record<string, never>;
    res: Record<string, never>;
  };
  "Tasks.Toggle": {
    req: types.ToggleTaskParams;
    res: types.Task;
  };
}

const metadata = {
  "Devtools.Info": { path: "/Devtools/Info", primitive: "query" },
  "Devtools.Ping": { path: "/Devtools/Ping", primitive: "query" },
  "Devtools.Status": { path: "/Devtools/Status", primitive: "query" },
  "System.Kill": { path: "/System/Kill", primitive: "exec" },
  "Tasks.Create": { path: "/Tasks/Create", primitive: "exec" },
  "Tasks.List": { path: "/Tasks/List", primitive: "query" },
  "Tasks.MakeError": { path: "/Tasks/MakeError", primitive: "exec" },
  "Tasks.Toggle": { path: "/Tasks/Toggle", primitive: "exec" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
