// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "System.Kill": {
    req: Record<string, never>;
    res: Record<string, never>;
  };
  "Tasks.Create": {
    req: types.CreateTaskParams;
    res: types.Task;
  };
  "Tasks.List": {
    req: types.ListTasksParams;
    res: (types.Task | null)[];
  };
  "Tasks.MakeError": {
    req: Record<string, never>;
    res: Record<string, never>;
  };
  "Tasks.SyncedList": {
    req: Record<string, never>;
    res: (types.Task | null)[];
    primitive: "atom";
  };
  "Tasks.Time": {
    req: Record<string, never>;
    res: types.TimeUpdate;
    primitive: "stream";
  };
  "Tasks.Toggle": {
    req: types.ToggleTaskParams;
    res: types.Task;
  };
}

const metadata = {
  "System.Kill": { path: "/System/Kill", primitive: "exec" },
  "Tasks.Create": { path: "/Tasks/Create", primitive: "exec" },
  "Tasks.List": { path: "/Tasks/List", primitive: "query" },
  "Tasks.MakeError": { path: "/Tasks/MakeError", primitive: "exec" },
  "Tasks.SyncedList": { path: "/Tasks/SyncedList", primitive: "atom" },
  "Tasks.Time": { path: "/Tasks/Time", primitive: "stream" },
  "Tasks.Toggle": { path: "/Tasks/Toggle", primitive: "exec" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
