// Code generated by tygor. DO NOT EDIT.

/**
 * CreateTaskParams contains parameters for creating a task.
 * @see github.com/broady/tygor/examples/devtools/api/types.go#CreateTaskParams
 */
export interface CreateTaskParams {
  title: string;
}
/**
 * ListTasksParams contains parameters for listing tasks.
 * @see github.com/broady/tygor/examples/devtools/api/types.go#ListTasksParams
 */
export interface ListTasksParams {
  /** ShowDone filters to show completed tasks. */
  show_done?: boolean;
}
/**
 * Task represents a todo item.
 * @see github.com/broady/tygor/examples/devtools/api/types.go#Task
 */
export interface Task {
  /** ID is the unique identifier. */
  id: number /* int32 */;
  /** Title is the task description. */
  title: string;
  /** Done indicates if the task is completed. */
  done: boolean;
}
/**
 * TimeUpdate is sent by the time stream every second.
 * @see github.com/broady/tygor/examples/devtools/api/types.go#TimeUpdate
 */
export interface TimeUpdate {
  time: string /* RFC3339 */;
}
/**
 * ToggleTaskParams identifies which task to toggle.
 * @see github.com/broady/tygor/examples/devtools/api/types.go#ToggleTaskParams
 */
export interface ToggleTaskParams {
  id: number /* int32 */;
}
