// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "Message.Set": {
    req: types.SetMessageParams;
    res: types.MessageState;
  };
  "Message.State": {
    req: Record<string, never>;
    res: types.MessageState;
    primitive: "atom";
  };
}

const metadata = {
  "Message.Set": { path: "/Message/Set", primitive: "exec" },
  "Message.State": { path: "/Message/State", primitive: "atom" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
