// Code generated by tygor. DO NOT EDIT.

import { z } from 'zod';
import * as s from './schemas.zod';

export const schemaMap = {
  "Message.Set": {
    request: s.SetMessageParamsSchema,
    response: s.MessageStateSchema,
  },
  "Message.State": {
    request: z.object({}),
    response: s.MessageStateSchema,
  },
} as const;

export type SchemaMap = typeof schemaMap;
