// Code generated by tygor. DO NOT EDIT.

import { z } from 'zod';

export const MessageStateSchema = z.object({
  message: z.string(),
  set_count: z.number().int().min(-2147483648).max(2147483647), // int32
});

export const SetMessageParamsSchema = z.object({
  message: z.string().min(1).min(2).max(10), // validate:"required,min=2,max=10"
});

