// Code generated by tygor. DO NOT EDIT.

/**
 * MessageState holds the current message and how many times it's been set.
 * @see main/types.go#MessageState
 */
export interface MessageState {
  /** Message is the current message (5-10 characters). */
  message: string;
  /** SetCount is the number of times the message has been set. */
  set_count: number /* int32 */;
}
/**
 * SetMessageParams contains the new message value.
 * @see main/types.go#SetMessageParams
 */
export interface SetMessageParams {
  message: string;
}
