// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "News.Create": {
    req: types.CreateNewsParams;
    res: types.News;
  };
  "News.List": {
    req: types.ListNewsParams;
    res: types.News[];
  };
}

const metadata = {
  "News.Create": { path: "/News/Create", primitive: "exec" },
  "News.List": { path: "/News/List", primitive: "query" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
