// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "News.Create": {
    req: types.CreateNewsParams;
    res: types.News;
  };
  "News.List": {
    req: types.ListNewsParams;
    res: types.News[];
  };
}

const metadata = {
  "News.Create": { method: "POST", path: "/News/Create" },
  "News.List": { method: "GET", path: "/News/List" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
