// Code generated by tygor. DO NOT EDIT.
import { ServiceRegistry } from '@tygor/client';
import * as types from './types';

export interface RPCManifest {
  "News.Create": {
    req: types.CreateNewsParams;
    res: types.News;
  };
  "News.List": {
    req: types.ListNewsParams;
    res: types.News[];
  };
}

const metadata = {
  "News.Create": { method: "POST", path: "/News/Create" },
  "News.List": { method: "GET", path: "/News/List" },
} as const;

export const registry: ServiceRegistry<RPCManifest> = {
  manifest: {} as RPCManifest,
  metadata,
};
