// Code generated by tygor. DO NOT EDIT.

// Branded types for enhanced type safety
export type DateTime = string & { readonly __brand: 'DateTime' };

// DateTime helper functions
export const DateTime = {
  // Create DateTime from string (assumes valid ISO 8601)
  from: (s: string): DateTime => s as DateTime,

  // Get current timestamp as DateTime
  now: (): DateTime => new Date().toISOString() as DateTime,

  // Parse DateTime to Date object
  toDate: (dt: DateTime): Date => new Date(dt),

  // Format DateTime for display
  format: (dt: DateTime, locale = 'en-US'): string => {
    return new Date(dt).toLocaleString(locale);
  },
};

/** CreateNewsParams contains the parameters for creating a new news article. */
export interface CreateNewsParams {
  title: string;
  body?: string;
}
/** ListNewsParams contains pagination parameters for listing news articles. */
export interface ListNewsParams {
  limit: number | null;
  offset: number | null;
}
/** News represents a news article in the system. */
export interface News {
  /** ID is the unique identifier for the article. */
  id: number;
  /** Title is the article headline. */
  title: string;
  /** Body is the optional article content. */
  body?: string;
  /** Status is the current publication status of the article. */
  status: NewsStatus;
  /** CreatedAt is the timestamp when the article was created. */
  created_at?: DateTime;
}
/** NewsStatus represents the publication status of a news article. */
export type NewsStatus = "archived" | "draft" | "published";
