// Code generated by tygor. DO NOT EDIT.

// Branded types for enhanced type safety
export type DateTime = string & { readonly __brand: 'DateTime' };

// DateTime helper functions
export const DateTime = {
  // Create DateTime from string (assumes valid ISO 8601)
  from: (s: string): DateTime => s as DateTime,

  // Get current timestamp as DateTime
  now: (): DateTime => new Date().toISOString() as DateTime,

  // Parse DateTime to Date object
  toDate: (dt: DateTime): Date => new Date(dt),

  // Format DateTime for display
  format: (dt: DateTime, locale = 'en-US'): string => {
    return new Date(dt).toLocaleString(locale);
  },
};

export interface CreateNewsParams {
  title: string;
  body?: string;
}
export interface ListNewsParams {
  limit: number | null;
  offset: number | null;
}
export interface News {
  id: number;
  title: string;
  body?: string;
  status: NewsStatus;
  created_at?: DateTime;
}
export type NewsStatus = string;
