// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export interface News {
  id: number /* int32 */;
  title: string;
  body?: string;
  created_at?: string;
}
export interface ListNewsParams {
  limit?: number /* int32 */;
  offset?: number /* int32 */;
}
export interface CreateNewsParams {
  title: string;
  body?: string;
}
