// Code generated by tygor. DO NOT EDIT.

export interface CreateNewsParams {
  title: string;
  body?: string;
}
export interface ListNewsParams {
  limit: number | null;
  offset: number | null;
}
export interface News {
  id: number;
  title: string;
  body?: string;
  status: NewsStatus;
  created_at?: string;
}
export type NewsStatus = string;
