// Code generated by tygor. DO NOT EDIT.

import * as types from './types';

export interface Manifest {
  "Comments.Create": {
    req: types.CreateCommentRequest;
    res: types.Comment;
  };
  "Comments.List": {
    req: types.ListCommentsParams;
    res: types.Comment[];
  };
  "Posts.Create": {
    req: types.CreatePostRequest;
    res: types.Post;
  };
  "Posts.Get": {
    req: types.GetPostParams;
    res: types.Post;
  };
  "Posts.List": {
    req: types.ListPostsParams;
    res: types.Post[];
  };
  "Posts.Publish": {
    req: types.PublishPostRequest;
    res: types.Post;
  };
  "Posts.Update": {
    req: types.UpdatePostRequest;
    res: types.Post;
  };
  "Users.Create": {
    req: types.CreateUserRequest;
    res: types.User;
  };
  "Users.Login": {
    req: types.LoginRequest;
    res: types.LoginResponse;
  };
}

const metadata = {
  "Comments.Create": { path: "/Comments/Create", primitive: "exec" },
  "Comments.List": { path: "/Comments/List", primitive: "query" },
  "Posts.Create": { path: "/Posts/Create", primitive: "exec" },
  "Posts.Get": { path: "/Posts/Get", primitive: "query" },
  "Posts.List": { path: "/Posts/List", primitive: "query" },
  "Posts.Publish": { path: "/Posts/Publish", primitive: "exec" },
  "Posts.Update": { path: "/Posts/Update", primitive: "exec" },
  "Users.Create": { path: "/Users/Create", primitive: "exec" },
  "Users.Login": { path: "/Users/Login", primitive: "exec" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
