// Code generated by tygor. DO NOT EDIT.
import { ServiceRegistry } from '@tygor/client';
import * as types from './types';

export interface Manifest {
  "Comments.Create": {
    req: types.CreateCommentRequest;
    res: types.Comment;
  };
  "Comments.List": {
    req: types.ListCommentsParams;
    res: types.Comment[];
  };
  "Posts.Create": {
    req: types.CreatePostRequest;
    res: types.Post;
  };
  "Posts.Get": {
    req: types.GetPostParams;
    res: types.Post;
  };
  "Posts.List": {
    req: types.ListPostsParams;
    res: types.Post[];
  };
  "Posts.Publish": {
    req: types.PublishPostRequest;
    res: types.Post;
  };
  "Posts.Update": {
    req: types.UpdatePostRequest;
    res: types.Post;
  };
  "Users.Create": {
    req: types.CreateUserRequest;
    res: types.User;
  };
  "Users.Login": {
    req: types.LoginRequest;
    res: types.LoginResponse;
  };
}

const metadata = {
  "Comments.Create": { method: "POST", path: "/Comments/Create" },
  "Comments.List": { method: "GET", path: "/Comments/List" },
  "Posts.Create": { method: "POST", path: "/Posts/Create" },
  "Posts.Get": { method: "GET", path: "/Posts/Get" },
  "Posts.List": { method: "GET", path: "/Posts/List" },
  "Posts.Publish": { method: "POST", path: "/Posts/Publish" },
  "Posts.Update": { method: "POST", path: "/Posts/Update" },
  "Users.Create": { method: "POST", path: "/Users/Create" },
  "Users.Login": { method: "POST", path: "/Users/Login" },
} as const;

export const registry: ServiceRegistry<Manifest> = {
  manifest: {} as Manifest,
  metadata,
};
