// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

/**
 * User represents a user in the system.
 */
export interface User {
  id: number /* int64 */;
  username: string;
  email: string;
  created_at: string;
}
/**
 * Post represents a blog post.
 */
export interface Post {
  id: number /* int64 */;
  author_id: number /* int64 */;
  title: string;
  content: string;
  published: boolean;
  created_at: string;
  updated_at: string;
}
/**
 * Comment represents a comment on a post.
 */
export interface Comment {
  id: number /* int64 */;
  post_id: number /* int64 */;
  author_id: number /* int64 */;
  content: string;
  created_at: string;
}
/**
 * CreateUserRequest is the request to create a new user.
 */
export interface CreateUserRequest {
  username: string;
  email: string;
  password: string;
}
/**
 * LoginRequest is the request to login.
 */
export interface LoginRequest {
  email: string;
  password: string;
}
/**
 * LoginResponse contains the authentication token.
 */
export interface LoginResponse {
  token: string;
  user?: User;
}
/**
 * CreatePostRequest is the request to create a new post.
 */
export interface CreatePostRequest {
  title: string;
  content: string;
}
/**
 * UpdatePostRequest is the request to update a post.
 */
export interface UpdatePostRequest {
  post_id: number /* int64 */;
  title?: string;
  content?: string;
}
/**
 * ListPostsParams are the query parameters for listing posts.
 */
export interface ListPostsParams {
  author_id?: number /* int64 */;
  published?: boolean;
  limit: number /* int32 */;
  offset: number /* int32 */;
}
/**
 * GetPostParams are the query parameters for getting a post.
 */
export interface GetPostParams {
  post_id: number /* int64 */;
}
/**
 * PublishPostRequest marks a post as published.
 */
export interface PublishPostRequest {
  post_id: number /* int64 */;
}
/**
 * CreateCommentRequest is the request to create a comment.
 */
export interface CreateCommentRequest {
  post_id: number /* int64 */;
  content: string;
}
/**
 * ListCommentsParams are the query parameters for listing comments.
 */
export interface ListCommentsParams {
  post_id: number /* int64 */;
  limit: number /* int32 */;
  offset: number /* int32 */;
}
