// Code generated by tygor. DO NOT EDIT.

/** Comment represents a comment on a post. */
export interface Comment {
  id: number;
  post_id: number;
  author_id: number;
  content: string;
  created_at: string;
}
/** CreateCommentRequest is the request to create a comment. */
export interface CreateCommentRequest {
  post_id: number;
  content: string;
}
/** CreatePostRequest is the request to create a new post. */
export interface CreatePostRequest {
  title: string;
  content: string;
}
/** CreateUserRequest is the request to create a new user. */
export interface CreateUserRequest {
  username: string;
  email: string;
  password: string;
}
/** GetPostParams are the query parameters for getting a post. */
export interface GetPostParams {
  post_id: number;
}
/** ListCommentsParams are the query parameters for listing comments. */
export interface ListCommentsParams {
  post_id: number;
  limit: number;
  offset: number;
}
/** ListPostsParams are the query parameters for listing posts. */
export interface ListPostsParams {
  author_id?: number;
  published?: boolean;
  limit: number;
  offset: number;
}
/** LoginRequest is the request to login. */
export interface LoginRequest {
  email: string;
  password: string;
}
/** LoginResponse contains the authentication token. */
export interface LoginResponse {
  token: string;
  user?: User;
}
/** Post represents a blog post. */
export interface Post {
  id: number;
  author_id: number;
  title: string;
  content: string;
  published: boolean;
  created_at: string;
  updated_at: string;
}
/** PublishPostRequest marks a post as published. */
export interface PublishPostRequest {
  post_id: number;
}
/** UpdatePostRequest is the request to update a post. */
export interface UpdatePostRequest {
  post_id: number;
  title?: string;
  content?: string;
}
/** User represents a user in the system. */
export interface User {
  id: number;
  username: string;
  email: string;
  created_at: string;
}
