// Code generated by tygor. DO NOT EDIT.

export interface Comment {
  id: number;
  post_id: number;
  author_id: number;
  content: string;
  created_at: string;
}
export interface CreateCommentRequest {
  post_id: number;
  content: string;
}
export interface CreatePostRequest {
  title: string;
  content: string;
}
export interface CreateUserRequest {
  username: string;
  email: string;
  password: string;
}
export interface GetPostParams {
  post_id: number;
}
export interface ListCommentsParams {
  post_id: number;
  limit: number;
  offset: number;
}
export interface ListPostsParams {
  author_id: number | null;
  published: boolean | null;
  limit: number;
  offset: number;
}
export interface LoginRequest {
  email: string;
  password: string;
}
export interface LoginResponse {
  token: string;
  user: User | null;
}
export interface Post {
  id: number;
  author_id: number;
  title: string;
  content: string;
  published: boolean;
  created_at: string;
  updated_at: string;
}
export interface PublishPostRequest {
  post_id: number;
}
export interface UpdatePostRequest {
  post_id: number;
  title?: string;
  content?: string;
}
export interface User {
  id: number;
  username: string;
  email: string;
  created_at: string;
}
