// Code generated by tygor. DO NOT EDIT.

/**
 * Comment represents a comment on a post.
 * @see github.com/broady/tygor/examples/blog/api/types.go#Comment
 */
export interface Comment {
  id: number /* int64 */;
  post_id: number /* int64 */;
  author_id: number /* int64 */;
  content: string;
  created_at: string /* RFC3339 */;
}
/**
 * CreateCommentRequest is the request to create a comment.
 * @see github.com/broady/tygor/examples/blog/api/types.go#CreateCommentRequest
 */
export interface CreateCommentRequest {
  post_id: number /* int64 */;
  content: string;
}
/**
 * CreatePostRequest is the request to create a new post.
 * @see github.com/broady/tygor/examples/blog/api/types.go#CreatePostRequest
 */
export interface CreatePostRequest {
  title: string;
  content: string;
}
/**
 * CreateUserRequest is the request to create a new user.
 * @see github.com/broady/tygor/examples/blog/api/types.go#CreateUserRequest
 */
export interface CreateUserRequest {
  username: string;
  email: string;
  password: string;
}
/**
 * GetPostParams are the query parameters for getting a post.
 * @see github.com/broady/tygor/examples/blog/api/types.go#GetPostParams
 */
export interface GetPostParams {
  post_id: number /* int64 */;
}
/**
 * ListCommentsParams are the query parameters for listing comments.
 * @see github.com/broady/tygor/examples/blog/api/types.go#ListCommentsParams
 */
export interface ListCommentsParams {
  post_id: number /* int64 */;
  limit: number /* int32 */;
  offset: number /* int32 */;
}
/**
 * [snippet:query-params]
 * ListPostsParams are the query parameters for listing posts.
 * @see github.com/broady/tygor/examples/blog/api/types.go#ListPostsParams
 */
export interface ListPostsParams {
  author_id?: number /* int64 */;
  published?: boolean;
  limit: number /* int32 */;
  offset: number /* int32 */;
}
/**
 * LoginRequest is the request to login.
 * @see github.com/broady/tygor/examples/blog/api/types.go#LoginRequest
 */
export interface LoginRequest {
  email: string;
  password: string;
}
/**
 * LoginResponse contains the authentication token.
 * @see github.com/broady/tygor/examples/blog/api/types.go#LoginResponse
 */
export interface LoginResponse {
  token: string;
  user?: User;
}
/**
 * Post represents a blog post.
 * @see github.com/broady/tygor/examples/blog/api/types.go#Post
 */
export interface Post {
  id: number /* int64 */;
  author_id: number /* int64 */;
  title: string;
  content: string;
  published: boolean;
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}
/**
 * PublishPostRequest marks a post as published.
 * @see github.com/broady/tygor/examples/blog/api/types.go#PublishPostRequest
 */
export interface PublishPostRequest {
  post_id: number /* int64 */;
}
/**
 * UpdatePostRequest is the request to update a post.
 * @see github.com/broady/tygor/examples/blog/api/types.go#UpdatePostRequest
 */
export interface UpdatePostRequest {
  post_id: number /* int64 */;
  title?: string;
  content?: string;
}
/**
 * User represents a user in the system.
 * @see github.com/broady/tygor/examples/blog/api/types.go#User
 */
export interface User {
  id: number /* int64 */;
  username: string;
  email: string;
  created_at: string /* RFC3339 */;
}
